
services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/app/
    ports:
      - "8000:8000"
    env_file:
      - ".env"

  postgres:
    image: "postgres:17.6-bookworm"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
