"""Make deadline timedelta

Revision ID: d61f7a037352
Revises: 385751baffee
Create Date: 2025-09-02 17:47:08.093326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61f7a037352'
down_revision = '385751baffee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=True,
               postgresql_using="make_interval(mins => duration)")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
